name: Publish package to npm registry

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    name: build and publish package to npm registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Doing a clean installation of dependencies
        run: pnpm install
      - name: build the package
        run: pnpm run release
      - name: Publish package to npm registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
